# Generated by Django 4.1 on 2022-08-23 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=625, verbose_name='Название задания')),
                ('priority', models.CharField(choices=[('Без приоритета', 'Без приоритета'), ('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий'), ('Очень срочно', 'Очень срочно')], default='Без приоритета', max_length=56, verbose_name='Приоритет задачи')),
                ('due_date', models.DateField(verbose_name='Срок выполнения')),
                ('is_done', models.BooleanField(verbose_name='Выполнено ли задание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.category', verbose_name='Категория задания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец задания')),
            ],
        ),
    ]
