# Generated by Django 4.1 on 2022-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_priority_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(max_length=56, null=True, verbose_name='Цвет приоритета'),
        ),
    ]
