# Generated by Django 4.1 on 2022-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_priority_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=models.CharField(max_length=7, null=True, verbose_name='Цвет приоритета'),
        ),
    ]
