# Generated by Django 4.1 on 2022-09-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_options_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
