# Generated by Django 4.1 on 2022-09-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_task_is_done'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='priority',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_user_priority'),
        ),
    ]
